const mockSoup = {
  meals: [
    {
      idMeal: '52973',
      strMeal: 'Leblebi Soup',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Tunisian',
      strInstructions: 'Heat the oil in a large pot. Add the onion and cook until translucent.\r\nDrain the soaked chickpeas and add them to the pot together with the vegetable stock. Bring to the boil, then reduce the heat and cover. Simmer for 30 minutes.\r\nIn the meantime toast the cumin in a small ungreased frying pan, then grind them in a mortar. Add the garlic and salt and pound to a fine paste.\r\nAdd the paste and the harissa to the soup and simmer until the chickpeas are tender, about 30 minutes.\r\nSeason to taste with salt, pepper and lemon juice and serve hot.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/x2fw9e1560460636.jpg',
      strTags: 'Soup',
      strYoutube: 'https://www.youtube.com/watch?v=BgRifcCwinY',
      strIngredient1: 'Olive Oil',
      strIngredient2: 'Onion',
      strIngredient3: 'Chickpeas',
      strIngredient4: 'Vegetable Stock',
      strIngredient5: 'Cumin',
      strIngredient6: 'Garlic',
      strIngredient7: 'Salt',
      strIngredient8: 'Harissa Spice',
      strIngredient9: 'Pepper',
      strIngredient10: 'Lime',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '2 tbs',
      strMeasure2: '1 medium finely diced',
      strMeasure3: '250g',
      strMeasure4: '1.5L',
      strMeasure5: '1 tsp ',
      strMeasure6: '5 cloves',
      strMeasure7: '1/2 tsp',
      strMeasure8: '1 tsp ',
      strMeasure9: 'Pinch',
      strMeasure10: '1/2 ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'http://allrecipes.co.uk/recipe/43419/leblebi--tunisian-chickpea-soup-.aspx',
      dateModified: null,
    },
    {
      idMeal: '52941',
      strMeal: 'Red Peas Soup',
      strDrinkAlternate: null,
      strCategory: 'Beef',
      strArea: 'Jamaican',
      strInstructions: 'Wash and rinse the dried kidney beans.. then cover with water in a deep bowl. Remember as they soak they will expand to at least triple the size they were originally so add a lot of water to the bowl. Soak them overnight or for at least 2 hrs to make the cooking step go quicker. I tossed out the water they were soaked in after it did the job.\r\n\r\nHave your butcher cut the salted pigtail into 2 inch pieces as it will be very difficult to cut with an ordinary kitchen knife. Wash, then place a deep pot with water and bring to a boil. Cook for 20 minutes, then drain + rinse and repeat (boil again in water). The goal is to make the pieces of pig tails tender and to remove most of the salt it was cured in.\r\n\r\nTime to start the soup. Place everything in the pot (except the flour and potato), then cover with water and place on a high flame to bring to a boil. As it comes to a boil, skim off any scum/froth at the top and discard. Reduce the heat to a gentle boil and allow it to cook for 1 hr and 15 mins.. basically until the beans are tender and start falling apart.\r\n\r\nIt’s now time to add the potato (and Yams etc if you’re adding it) as well as the coconut milk and continue cooking for 15 minutes.\r\n\r\nNow is a good time to start making the basic dough for the spinner dumplings. Mix the flour and water (add a pinch of salt if you want) until you have a soft/smooth dough. allow it to rest for 5 minutes, then pinch of a tablespoon at a time and roll between your hands to form a cigarette shape.\r\n\r\nAdd them to the pot, stir well and continue cooking for another 15 minutes on a rolling boil.\r\n\r\nYou’ll notice that I didn’t add any salt to the pot as the remaining salt from the salted pigtails will be enough to properly season this dish. However you can taste and adjust accordingly. Lets recap the timing part of things so you’re not confused. Cook the base of the soup for 1 hr and 15 minute or until tender, then add the potatoes and cook for 15 minutes, then add the dumplings and cook for a further 15 minutes. Keep in mind that this soup will thicken quite a bit as it cools.\r\n\r\nWhile this is not a traditional recipe to any one specific island, versions of this soup (sometimes called stewed peas) can be found throughout the Caribbean, Latin America and Africa. A hearty bowl of this soup will surely give you the sleepies (some may call it ethnic fatigue). You can certainly freeze the leftovers and heat it up another day.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/sqpqtp1515365614.jpg',
      strTags: 'Soup,SideDish',
      strYoutube: 'https://www.youtube.com/watch?v=1ogCfDXotMw',
      strIngredient1: 'Kidney Beans',
      strIngredient2: 'Carrots',
      strIngredient3: 'Spring Onions',
      strIngredient4: 'Thyme',
      strIngredient5: 'Onion',
      strIngredient6: 'Black Pepper',
      strIngredient7: 'Red Pepper',
      strIngredient8: 'Garlic Clove',
      strIngredient9: 'Allspice',
      strIngredient10: 'Beef',
      strIngredient11: 'Water',
      strIngredient12: 'Potatoes',
      strIngredient13: 'Plain Flour',
      strIngredient14: 'Water',
      strIngredient15: 'Coconut Milk',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '2 cups ',
      strMeasure2: '1 large',
      strMeasure3: '2 chopped',
      strMeasure4: '4 sprigs',
      strMeasure5: '1 Diced',
      strMeasure6: '1/2 tsp',
      strMeasure7: '2 chopped',
      strMeasure8: '4 Mashed',
      strMeasure9: '1 tbs',
      strMeasure10: '2 Lbs',
      strMeasure11: '2L',
      strMeasure12: '4',
      strMeasure13: '1 cup ',
      strMeasure14: '1/4 cup',
      strMeasure15: '1 cup ',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://caribbeanpot.com/caribbean-red-peas-soup/',
      dateModified: null,
    },
  ],
};

export default mockSoup;
