const details = {
  idDrink: '13332',
  strDrink: 'B-53',
  strCategory: 'Shot',
  strAlcoholic: 'Alcoholic',
  strInstructions: 'Layer the Kahlua, Sambucca and Grand Marnier into a shot glas in tha',
  strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rwqxrv1461866023.jpg',
  strIngredient1: 'Kahlua',
  strIngredient2: 'Sambuca',
  strIngredient3: 'Grand Marnier',
  strIngredient4: null,
  strIngredient5: null,
  strIngredient6: null,
  strIngredient7: null,
  strIngredient8: null,
  strIngredient9: null,
  strIngredient10: null,
  strIngredient11: null,
  strIngredient12: null,
  strIngredient13: null,
  strIngredient14: null,
  strIngredient15: null,
  strMeasure1: '1/3 shot ',
  strMeasure2: '1/3 shot ',
  strMeasure3: '1/3 shot ',
  strMeasure4: null,
  strMeasure5: null,
  strMeasure6: null,
  strMeasure7: null,
  strMeasure8: null,
  strMeasure9: null,
  strMeasure10: null,
  strMeasure11: null,
  strMeasure12: null,
  strMeasure13: null,
  strMeasure14: null,
  strMeasure15: null,
  strImageSource: null,
  strImageAttribution: null,
  strCreativeCommonsConfirmed: 'No',
  dateModified: '2016-04-28 18:53:43',
};

export default details;
